# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-nginx-deployment
  namespace: wazuh
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: wazuh-nginx
        image: nginx:1.23.2-alpine
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
